# Generated by Django 2.2.6 on 2019-10-22 13:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssentialOil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbr', models.CharField(max_length=10)),
                ('scientific_name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=100)),
                ('graph', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Metabolite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Through',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mzratio', models.FloatField()),
                ('time', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('relative_abundance1', models.FloatField()),
                ('relative_abundance2', models.FloatField()),
                ('relative_abundance3', models.FloatField()),
                ('relative_abundance4', models.FloatField()),
                ('metabolite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Metabolite')),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EssentialOil')),
            ],
        ),
    ]
